## Data Cleaning

In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('joined_results.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 403967 entries, 0 to 403966
Data columns (total 27 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   event_id          403967 non-null  int64
 1   ad_id             403967 non-null  int64
 2   user_id           403967 non-null  str
 3   timestamp         403967 non-null  str
 4   day_of_week       403967 non-null  str
 5   time_of_day       403967 non-null  str
 6   event_type        403967 non-null  str
 7   ad_id:1           403967 non-null  int64
 8   campaign_id       403967 non-null  int64
 9   ad_platform       403967 non-null  str
 10  ad_type           403967 non-null  str
 11  target_gender     403967 non-null  str
 12  target_age_group  403967 non-null  str
 13  target_interests  403967 non-null  str
 14  campaign_id:1     403967 non-null  int64
 15  name              403967 non-null  str
 16  start_date        403967 non-null  str
 17  end_date          403967 non-null  str
 18  duration_days     403967 non-null  int64
 19  total_budget      403967 non-null  float64
 20  user_id:1         403967 non-null  str
 21  user_gender       403967 non-null  str
 22  user_age          403967 non-null  int64
 23  age_group         403967 non-null  str
 24  country           403967 non-null  str
 25  location          403967 non-null  str
 26  interests         403967 non-null  str
dtypes: float64(1), int64(7), str(19)
memory usage: 83.2 MB

In [34]:
# Convert to appropriate data types

cols_to_convert = ['start_date','end_date','timestamp']
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_datetime)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 403967 entries, 0 to 403966
Data columns (total 27 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   event_id          403967 non-null  int64
 1   ad_id             403967 non-null  int64
 2   user_id           403967 non-null  str
 3   timestamp         403967 non-null  datetime64[us]
 4   day_of_week       403967 non-null  str
 5   time_of_day       403967 non-null  str
 6   event_type        403967 non-null  str
 7   ad_id:1           403967 non-null  int64
 8   campaign_id       403967 non-null  int64
 9   ad_platform       403967 non-null  str
 10  ad_type           403967 non-null  str
 11  target_gender     403967 non-null  str
 12  target_age_group  403967 non-null  str
 13  target_interests  403967 non-null  str
 14  campaign_id:1     403967 non-null  int64
 15  name              403967 non-null  str
 16  start_date        403967 non-null  datetime64[us]
 17  end_date          403967 non-null  datetime64[us]
 18  duration_days     403967 non-null  int64
 19  total_budget      403967 non-null  float64
 20  user_id:1         403967 non-null  str
 21  user_gender       403967 non-null  str
 22  user_age          403967 non-null  int64
 23  age_group         403967 non-null  str
 24  country           403967 non-null  str
 25  location          403967 non-null  str
 26  interests         403967 non-null  str
dtypes: datetime64[us](3), float64(1), int64(7), str(16)
memory usage: 83.2 MB

In [ ]:
# Basic descriptive statistics

df.describe().round(2)

# Likely duplicated entries since event_id counts of 403,967 is more than its max number of 400,000.

,event_id,ad_id,timestamp,ad_id:1,campaign_id,campaign_id:1,start_date,end_date,duration_days,total_budget,user_age
count,403967.00,403967.00,403967,403967.00,403967.00,403967.00,403967,403967,403967.00,403967.00,403967.00
mean,200034.50,100.52,2025-06-22 01:10:07.907782,100.52,25.13,25.13,2025-05-01 18:50:28.257258,2025-07-07 03:53:29.492854,66.38,51166.91,27.69
min,1.00,1.00,2025-05-07 14:11:57,1.00,1.00,1.00,2025-02-13 00:00:00,2025-04-02 00:00:00,32.00,7918.04,16.00
25%,100030.50,51.00,2025-05-30 07:56:23,51.00,13.00,13.00,2025-04-01 00:00:00,2025-06-01 00:00:00,52.00,28962.34,21.00
50%,200044.00,101.00,2025-06-22 00:12:50,101.00,25.00,25.00,2025-04-24 00:00:00,2025-07-04 00:00:00,70.00,48832.61,27.00
75%,300051.50,151.00,2025-07-14 19:46:19.500000,151.00,37.00,37.00,2025-06-04 00:00:00,2025-08-05 00:00:00,82.00,71626.83,32.00
max,400000.00,200.00,2025-08-06 14:11:30,200.00,50.00,50.00,2025-07-23 00:00:00,2025-10-12 00:00:00,90.00,98904.66,65.00
std,115476.51,57.78,NaN,57.78,13.68,13.68,NaN,NaN,16.78,25583.22,8.32

In [38]:
# Check number of NULL values

df.isnull().sum()

event_id            0
ad_id               0
user_id             0
timestamp           0
day_of_week         0
time_of_day         0
event_type          0
ad_id:1             0
campaign_id         0
ad_platform         0
ad_type             0
target_gender       0
target_age_group    0
target_interests    0
campaign_id:1       0
name                0
start_date          0
end_date            0
duration_days       0
total_budget        0
user_id:1           0
user_gender         0
user_age            0
age_group           0
country             0
location            0
interests           0
dtype: int64

In [ ]:
# Checking for Outliers (keep due to valid users and no unreasonable user age value)

Q1 = df['user_age'].quantile(0.25)
Q3 = df['user_age'].quantile(0.75)
IQR = Q3-Q1

outliers = df[(df['user_age'] < Q1 - 1.5*IQR) | (df['user_age'] > Q3+1.5*IQR)]
print(outliers)

        event_id  ad_id user_id           timestamp day_of_week time_of_day  \
4              5     52   68f1a 2025-07-22 08:30:29     tuesday     morning
10            11     94   94d94 2025-05-28 05:56:08   wednesday       night
15            16    158   638d4 2025-05-24 23:16:41    saturday     evening
41            41     41   e5da3 2025-06-19 18:05:13    thursday     evening
104          104     96   da029 2025-06-08 20:00:58      sunday     evening
...          ...    ...     ...                 ...         ...         ...
403755    399793     85   3dd3b 2025-07-04 00:23:59      friday       night
403849    399887     41   9e923 2025-05-18 11:05:00      sunday     morning
403901    399936    103   f211b 2025-07-06 18:09:24      sunday     evening
403911    399946    111   e82f0 2025-05-23 21:44:42      friday     evening
403937    399971    192   c6943 2025-08-06 03:38:04   wednesday       night

        event_type  ad_id:1  campaign_id ad_platform  ...   end_date  \
4       impression       52            2   instagram  ... 2025-07-07
10      impression       94           14    facebook  ... 2025-06-04
15      impression      158           24   instagram  ... 2025-05-23
41      impression       41           38    facebook  ... 2025-05-27
104     impression       96           24    facebook  ... 2025-05-23
...            ...      ...          ...         ...  ...        ...
403755  impression       85           20    facebook  ... 2025-05-18
403849  impression       41           38    facebook  ... 2025-05-27
403901  impression      103           22    facebook  ... 2025-04-22
403911  impression      111           42    facebook  ... 2025-07-25
403937  impression      192           47    facebook  ... 2025-09-03

       duration_days total_budget user_id:1  user_gender user_age age_group  \
4                 82     79342.41     68f1a         male       58     55-65
10                50     39849.94     94d94       female       53     45-54
15                54     56692.87     638d4         male       65     55-65
41                36     71038.28     e5da3         male       50     45-54
104               54     56692.87     da029         male       52     45-54
...              ...          ...       ...          ...      ...       ...
403755            90     98904.66     3dd3b        other       49     45-54
403849            36     71038.28     9e923         male       50     45-54
403901            36     35743.40     f211b        other       50     45-54
403911            47      7918.04     e82f0         male       54     45-54
403937            78     69493.36     c6943        other       51     45-54

               country       location                   interests
4       united kingdom   robinsonberg          finance, lifestyle
10       united states     staceyview                travel, food
15      united kingdom    cameronfurt                      travel
41              canada    richardberg     sports, art, technology
104     united kingdom     west tyler                   food, art
...                ...            ...                         ...
403755  united kingdom  north richard  lifestyle, fashion, health
403849          brazil    teresamouth      lifestyle, photography
403901         germany      luisville             travel, fashion
403911         germany  north michael  fitness, health, lifestyle
403937          mexico   west matthew                        news

[8191 rows x 27 columns]

In [ ]:
# Check & Remove Partial Duplicates (3966 entries deleted due to conflicting ad entries with multiple users)

df_clean = df.drop_duplicates(subset=['event_id'])
df_clean.info()

<class 'pandas.DataFrame'>
Index: 400000 entries, 0 to 403966
Data columns (total 27 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   event_id          400000 non-null  int64
 1   ad_id             400000 non-null  int64
 2   user_id           400000 non-null  str
 3   timestamp         400000 non-null  datetime64[us]
 4   day_of_week       400000 non-null  str
 5   time_of_day       400000 non-null  str
 6   event_type        400000 non-null  str
 7   ad_id:1           400000 non-null  int64
 8   campaign_id       400000 non-null  int64
 9   ad_platform       400000 non-null  str
 10  ad_type           400000 non-null  str
 11  target_gender     400000 non-null  str
 12  target_age_group  400000 non-null  str
 13  target_interests  400000 non-null  str
 14  campaign_id:1     400000 non-null  int64
 15  name              400000 non-null  str
 16  start_date        400000 non-null  datetime64[us]
 17  end_date          400000 non-null  datetime64[us]
 18  duration_days     400000 non-null  int64
 19  total_budget      400000 non-null  float64
 20  user_id:1         400000 non-null  str
 21  user_gender       400000 non-null  str
 22  user_age          400000 non-null  int64
 23  age_group         400000 non-null  str
 24  country           400000 non-null  str
 25  location          400000 non-null  str
 26  interests         400000 non-null  str
dtypes: datetime64[us](3), float64(1), int64(7), str(16)
memory usage: 85.4 MB

In [ ]:
# Save clean data to csv file

df_clean.to_csv ('cleaned_joined_data.csv')

In [47]:
df_clean.head()

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type,ad_id:1,campaign_id,ad_platform,...,end_date,duration_days,total_budget,user_id:1,user_gender,user_age,age_group,country,location,interests
0,1,197,2359b,2025-07-26 00:19:56,saturday,night,like,197,9,facebook,...,2025-07-13,49,40094.07,2359b,female,24,18-24,united states,west shawna,"gaming, food"
1,2,51,f9c67,2025-06-15 08:28:07,sunday,morning,share,51,26,instagram,...,2025-06-17,77,44538.87,f9c67,female,30,25-34,united states,meyersland,"photography, finance"
2,3,46,5b868,2025-06-27 00:40:02,friday,night,impression,46,10,instagram,...,2025-07-21,65,19669.27,5b868,male,20,18-24,united states,barrerahaven,"fashion, sports, travel"
3,4,166,3d440,2025-06-05 19:20:45,thursday,evening,impression,166,14,instagram,...,2025-06-04,50,39849.94,3d440,female,18,18-24,united states,lake angelaland,"food, art"
4,5,52,68f1a,2025-07-22 08:30:29,tuesday,morning,impression,52,2,instagram,...,2025-07-07,82,79342.41,68f1a,male,58,55-65,united kingdom,robinsonberg,"finance, lifestyle"